compnerd/uswift

CMakeLists.txt
Source/CMakeLists.txt
Source/Core/CMakeLists.txt
Source/Onone/CMakeLists.txt
Source/Runtime/CMakeLists.txt

This updates the build to use CMake 3.18.  The result of that is that we
can use the modern Swift support in CMake to build the library.  It
greatly simplifies the handling.  While cleaning up the build rules,
attempt to support Windows and Darwin a bit better.

build: update to more modern CMake

---

Source/Runtime/CMakeLists.txt
Source/Runtime/Enum.c
Source/Runtime/HeapObject.c
Source/Runtime/KnownMetadata.c
Source/Runtime/Metadata.c
Source/Runtime/Types.h
Source/Runtime/Visibility.h

Ensure that we have placeholders for the referenced functions.  This
allows us to build a version of uSwift, even if it is unable to handle
these callouts.

Runtime: add additional stubs for building uSwift

---

Source/Core/Bool.swift
Source/Core/Int.swift
Source/Core/Int32.swift
Source/Core/Int8.swift
Source/Core/UInt.swift
Source/Core/UInt32.swift
Source/Core/UInt8.swift

The `@_fixed_layout` attribute has been replaced by `@frozen`.  Update
the sources to avoid the warning.

Core: replace `@_fixed_layout` with `@frozen`

---

Source/Core/Bool.swift
Source/Core/CompilerProtocols.swift
Source/Core/Equatable.swift
Source/Core/Int.swift
Source/Core/Int32.swift
Source/Core/Int8.swift
Source/Core/Integers.swift
Source/Core/Never.swift
Source/Core/OptionSet.swift
Source/Core/Optional.swift
Source/Core/Policy.swift
Source/Core/UInt.swift
Source/Core/UInt32.swift
Source/Core/UInt8.swift
Source/Core/Void.swift
Source/Runtime/Enum.c
Source/Runtime/HeapObject.c
Source/Runtime/KnownMetadata.c
Source/Runtime/Types.h
Source/Runtime/Visibility.h

Add missing copyright headers to the Core and Runtime libraries.

add copyright headers

---

Sources/Core/Optional.swift

Add the ability to compare optional values as being equal.  This change
has been sitting around for about 2 years locally amongst other changes.

Core: add equality for `Optional`

---

Sources/Core/Never.swift
Sources/Core/Optional.swift

The original `@_fixed_layout` attribute was replaced with `@_frozen`
which was then replaced with the accepted `@frozen` spelling.  Replace
the two instances of `@_frozen` with `@frozen` to be uniform in usage
throughout the implementation.

Core: use `@frozen` over `@_frozen`

---

Sources/Runtime/KnownMetadata.c
Sources/Runtime/Types.h

Use the common definitions rather than redefining macros everywhere.
Centralise the type declarations in `Types.h`.

Runtime: share the visibility types

---

Sources/Core/Policy.swift

Remove the type from the operator declaration as this has been removed in recent versions.

Core: adjust the operator declarations

---

Sources/CMakeLists.txt
Sources/_Concurrency/CMakeLists.txt

This is an empty module that silences compiler errors.

Add `_Concurrency` module.

---

.github/workflows/build.yml

Build shared libraries instead of static libraries.  This has two purposes:
1. Windows does not support static linking for Swift yet
2. This allows for ensuring that no undefined references remain
This already has helped catch a missing stub in the runtime, and will likely identify more missing entry points in the future.

CI: build shared libraries

---

Sources/Core/Policy.swift

Windows and Android do not support FP80 intentionally even on x86 architectures.  This allows for the 32-bit platform to match across architectures (FP32).

Policy: correct the FP width

---

Sources/Runtime/HeapObject.c
Sources/Runtime/Metadata.c

`stdlib.h` requires a presence of libc, which is not always available when targeting bare metal. Looks like `stddef.h` works just as well and doesn't need libc.

runtime: replace `stdlib.h` with `stddef.h`

---

Sources/Core/Int.swift
Sources/Core/UInt.swift

This conforms `Int` and `UInt` to the specification of teh types as per
Swift: that they are pointer word sized.  This also more clearly
indicates why the typealias approach is less preferable.

Core: use word storage in `Int` and `UInt`

---

Sources/Core/CMakeLists.txt
Sources/Core/Pointer.swift
Sources/Core/UnsafeMutablePointer.swift
Sources/Core/UnsafePointer.swift

This initializer is needed to fully implement `StaticString`.
Depends on #34.

Add `_Pointer` protocol with `init?(bitPattern:)`

---

Sources/Core/CMakeLists.txt
Sources/Core/UnsafeRawPointer.swift
Sources/Runtime/HeapObject.c

Add `UnsafeRawPointer` implementation

---

Sources/Core/Int.swift
Sources/Core/Int32.swift
Sources/Core/Int8.swift
Sources/Core/UInt.swift
Sources/Core/UInt32.swift
Sources/Core/UInt8.swift

This homogenises more of the operations on the integer types to use the proper
labels for paramters.  Additionally, use `Self` more aggressively for the
type.

Core: more style changes for integer types

---

Sources/Core/Builtin.swift
Sources/Core/CMakeLists.txt

This constant is used in some of the pointer allocation code.

Add `Builtin.swift` with `minAllocationAlignment`

---

Sources/Core/CMakeLists.txt
Sources/Core/CompilerProtocols.swift
Sources/Core/Policy.swift
Sources/Core/StaticString.swift

This implementation excludes a few properties that rely on `precondition`, which will be submitted as a separate PR.

Add `StaticString` implementation

---

.vscode/settings.json

I haven't been able to find satisfying formatting options for SwiftFormat yet, so disabling it for now.

Set ruler to 80 columns in `.vscode/settings.json`

---

.swiftformat
.vscode/settings.json

After tweaking a few settings, I think I actually found a combination of options that lines up function parameters as needed.

Re-enable SwiftFormat, add config file

---

.vscode/extensions.json
.vscode/settings.json

Avoid the automated cmake configure request on project open, exclude some files
from the file list, and add suggestions for CMake syntax highlighting, CMake
integration, and comment anchor extensions. The latter allows highlighting
specific tags.  Configure the default set of tags to highlight to include
"MARK", "TODO", "FIXME", "NOTE".

vscode: add some more default settings and suggestions

---

.swiftformat

This makes it more consistent with the rest of the codebase.

SwiftFormat: tweak function arguments wrapping

---

Sources/Runtime/HeapObject.c

`swift_slowAlloc` is supposed to return a pointer.

Runtime: fix missing return value warning

---

Sources/Core/Int.swift
Sources/Core/Int32.swift
Sources/Core/Int8.swift
Sources/Core/UInt.swift
Sources/Core/UInt32.swift
Sources/Core/UInt8.swift

This sorts the extensions lexicographically to make it easier to locate the
extension.  Additionally, more aggressively use `Self` for the conformances
which illustrates the values are meant to be the same "generic" type.

Core: adjust style for `{,U}Int{,8,32}`

---

.swiftformat

This matches the coding style of the project with ACL modifiers on specific declarations instead of grouping ACL with `public extension`.

SwiftFormat: tweak extensions ACL formatting

---

Sources/Core/CompilerProtocols.swift

Reflow an overly long line to adhere to 80-columns.

Core: reflow text in CompilerProtocols (NFC)

---

Sources/Core/CMakeLists.txt
Sources/Core/Int64.swift
Sources/Core/UInt64.swift

This completes the built-in sized integer types.  We now have the fixed-size
integers as well as the word sized integer types.

Core: introduce `Int64` and `UInt64`

---

Sources/Core/CMakeLists.txt
Sources/Core/Operators.swift
Sources/Core/SignedNumeric.swift

Depends on #55.
I'm not adding the default (and only) implementation here yet, as it crashes the type checker with `Assertion failed: (protocol && "requirements should have stopped recursion")` error message:
```swift
extension SignedNumeric {
@_transparent
public static prefix func - (_ operand: Self) -> Self {
var result = operand
result.negate()
return result
}
@_transparent
public mutating func negate() {
self = 0 - self
}
}
```

Core: add `SignedNumeric` protocol

---

Sources/Core/BinaryInteger.swift
Sources/Core/FixedWidthInteger.swift
Sources/Core/Int.swift
Sources/Core/Int16.swift
Sources/Core/Int32.swift
Sources/Core/Int64.swift
Sources/Core/Int8.swift
Sources/Core/UInt.swift
Sources/Core/UInt16.swift
Sources/Core/UInt32.swift
Sources/Core/UInt64.swift
Sources/Core/UInt8.swift

I've reduced the scope of `BinaryInteger` protocol here, leaving only `/`, `%` and their assignment variants `/=` and `%=`. The original declaration of the protocol is huge, I think reducing it makes it this PR more reviewable. More requirements and implementations will be added in future PRs.

Core: add basic `BinaryInteger` on integer types

---

.github/workflows/build.yml

Now that Swift 5.6 has been released, there doesn't seem to be a point in testing with 5.6 snapshots.

CI: use latest Swift 5.6.1 release

---

Sources/Core/BinaryInteger.swift

This is a trivial bug fix that closes #86.

Bugfix: make 'func /=' divide, not add.
